// src/app/layout.tsx

import type React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavbarProvider } from "@/components/NavbarContext";
import Providers from "./providers";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react"; // <-- 1. IMPORT SUSPENSE
import { PageWrapper } from "@/components/chatbot/page-wrapper"; // <-- 2. IMPORT PAGEWRAPPER

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {/* 3. WRAP YOUR EXISTING CONTENT WITH SUSPENSE AND PAGEWRAPPER */}
          <Suspense fallback={<div>Loading...</div>}>
            <PageWrapper>
              <NavbarProvider>{children}</NavbarProvider>
            </PageWrapper>
          </Suspense>
        </Providers>
        <Toaster
          theme="light"
          richColors
          toastOptions={{
            classNames: {
              error: "bg-red-600 text-white font-medium border-red-700",
              success: "text-green-600 bg-white font-medium border-green-700",
              warning: "text-yellow-600 bg-white font-medium border-yellow-700",
            },
          }}
        />
      </body>
    </html>
  );
}
